/**
 * Cross-links to other vertical sites in the network.
 * Auto-generated by the verticals hub sync-crosslinks script.
 * Do NOT edit manually.
 */

export interface CrossLink {
  name: string;
  domain: string;
  url: string;
  tagline: string;
}

export const crosslinks: CrossLink[] = [
  {
    "name": "PainterAI",
    "domain": "painterai.com",
    "url": "https://painterai.com",
    "tagline": ""
  },
  {
    "name": "HardscapeAI",
    "domain": "hardscapeai.com",
    "url": "https://hardscapeai.com",
    "tagline": ""
  }
];
