/**
 * Vertical Configuration — Single source of truth for this vertical site.
 * Generated by the verticals hub scaffold script from registry/windows-doors.json.
 * Do NOT edit manually — re-run the scaffold to update.
 */

export interface VerticalConfig {
  slug: string;
  brandName: string;
  domain: string;
  tagline: string;
  description: string;

  agent: {
    publicId: string | null;
    backendUrl: string;
    widgetUrl: string;
    phoneNumber: string | null;
  };

  theme: {
    primary: string;
    accent: string;
    success: string;
    warning: string;
  };

  industry: {
    name: string;
    shortName: string;
    avgTicket: string;
    painPoint: string;
    projectTypes: string[];
    commonSoftware: string[];
    leadSources: string[];
  };

  seo: {
    primaryKeywords: string[];
    metaPixelId: string | null;
  };

  social: Record<string, string>;
  calcomLink: string | null;
  relatedVerticals: Array<{
    name: string;
    domain: string;
    slug: string;
  }>;
}

export const config: VerticalConfig = {
  "slug": "windows-doors",
  "brandName": "windoAI",
  "domain": "windoai.com",
  "tagline": "AI Receptionist for Window & Door Companies",
  "description": "Never miss a window or door lead again. windoAI answers calls, qualifies projects, and books in-home estimates 24/7 — built for window and door manufacturers and installers.",
  "agent": {
    "publicId": "ag_bWJ4ezN8",
    "backendUrl": "https://backend-api-production-b536.up.railway.app",
    "widgetUrl": "https://backend-api-production-b536.up.railway.app/widget/v1/widget.js",
    "phoneNumber": null
  },
  "theme": {
    "primary": "#0891B2",
    "accent": "#06B6D4",
    "success": "#10B981",
    "warning": "#F59E0B"
  },
  "industry": {
    "name": "Window & Door Manufacturers and Installers",
    "shortName": "Window Companies",
    "avgTicket": "$10,000 - $30,000",
    "painPoint": "Speed-to-lead is critical — homeowners request 3-5 quotes and book with whoever responds first. Missing a call means losing a $15K-$30K job. Many companies both manufacture and install, so calls range from product inquiries to installation scheduling.",
    "projectTypes": [
      "Window Replacement",
      "Door Replacement",
      "Entry Door Installation",
      "Patio Door Installation",
      "Storm Windows",
      "Bay & Bow Windows",
      "Sliding Glass Doors",
      "Energy-Efficient Upgrades"
    ],
    "commonSoftware": [
      "MarketSharp",
      "Improveit 360",
      "Leap",
      "JobNimbus",
      "QuickBooks"
    ],
    "leadSources": [
      "Google Search",
      "HomeAdvisor",
      "Angi",
      "TV/Radio Ads",
      "Home Shows",
      "Referrals",
      "Door-to-Door"
    ]
  },
  "seo": {
    "primaryKeywords": [
      "AI receptionist for window companies",
      "window replacement answering service",
      "AI for window and door contractors",
      "window company lead management",
      "window replacement business automation"
    ],
    "metaPixelId": null
  },
  "social": {},
  "calcomLink": null,
  "relatedVerticals": [
    {
      "name": "PainterAI",
      "domain": "painterai.com",
      "slug": "painters"
    },
    {
      "name": "HardscapeAI",
      "domain": "hardscapeai.com",
      "slug": "hardscaping"
    }
  ]
};
